apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: glass-badge-397122
  artifacts:
    # - image: us.gcr.io/glass-badge-397122/auth
    - image: ofonseca/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync: 
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - ./infra/k8s/*
