apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          # image: us.gcr.io/glass-badge-397122/core
          image: ofonseca/core
          env:
            - name: MONGO_URI
              value: 'mongodb://core-mongo-srv:27017/core'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: core-srv
spec:
  selector:
    app: core
  ports:
    - name: core
      protocol: TCP
      port: 3000
      targetPort: 3000
